export { getGuideline, resolveGuideline, REFERENCES_HEADING_STYLE, CAPTION_STYLE } from './guidelines'
export type { Guideline, GuidelineSpec } from './guidelines'
export { listGuidelines } from './loadGuideline'
export type { GuidelineMeta } from './loadGuideline'
export { formatReferences, locateReferences, autoLocateReferences, pageForBlock } from './references'
export { locateAppendixStart, looksLikeAppendixHeading } from './postTextual'
export { detectPretextual, classifyPretextual, applyPretextualHeadings, applyCoverAlignment, applyFolhaRostoAlignment, applyPretextualPageBreaks, applyCoverVerticalDistribution, coverBlockIndices } from './preTextual'
export type { PretextualKind, PretextualSection, PretextualResult } from './preTextual'
export { formatCaptions } from './captions'
export { formatImages } from './imageLayout'
export { rewriteThemeFonts, normalizeFontPackaging } from './fontPackaging'
export { setRunFonts } from './setRunFonts'
export { setHeadingRunProps } from './setHeadingRunProps'
export { suppressFirstHeadingPageBreak, removeRedundantChapterPageBreaks } from './pageBreaks'
export { normalizeNumberingXml } from './normalizeNumbering'
export type { ReferencePagesInput, ReferenceRegion } from './references'
export { getBlocks, blockText } from './blocks'
export { stepD, chunkHeadings, applyHeadingDecisions } from './stepD'
export type { HeadingChunk, HeadingDecision, HeadingDecider, HeadingRole, StepDResult } from './stepD'
export { stepC, chunkReferences, applyReferenceDecisions, renderSegments, setParagraphRuns } from './stepC'
export type { ReferenceChunk, ReferenceEntry, ReferenceDecision, ReferenceDecider, ReferenceSegment, StepCResult } from './stepC'
export { stepProofread, chunkProofread, applyProofreadDecisions } from './stepProofread'
export type { ProofreadChunk, ProofreadBlock, ProofreadDecision, ProofreadDecider, StepProofreadResult } from './stepProofread'
export { loadAiConfig } from './ai/config'
export type { AiConfig } from './ai/config'
export { createHeadingDecider } from './ai/headingDecider'
export { createReferenceDecider } from './ai/referencesDecider'
export { createProofreadDecider } from './ai/proofreadDecider'
export { unzipDocx, zipDocx } from './docxZip'
export type { UnzippedDocx } from './docxZip'
export { rewriteStyles } from './rewriteStyles'
export { stripDirectOverrides } from './stripOverrides'
export { rewriteMargins } from './rewriteMargins'
export { applyStepA } from './applyStepA'
export type { StepAInput, StepAOutput } from './applyStepA'
export { applyPunctNorm, applyPunctNormWithStats, isNoopPunct } from './applyPunctNorm'
export type { PunctStats } from './applyPunctNorm'
export { detectAndInsertPlaceholders, finalizeInputs } from './missingInputs'
export type { MissingInputKind, PendingInput } from './missingInputs'
export { buildSumario } from './sumario'
export { demoteImplausibleHeadings } from './headingSanity'
