export { getGuideline, resolveGuideline, REFERENCES_HEADING_STYLE } from './guidelines'
export type { Guideline, GuidelineSpec } from './guidelines'
export { listGuidelines } from './loadGuideline'
export type { GuidelineMeta } from './loadGuideline'
export { formatReferences } from './references'
export type { ReferencePagesInput } from './references'
export { unzipDocx, zipDocx } from './docxZip'
export type { UnzippedDocx } from './docxZip'
export { rewriteStyles } from './rewriteStyles'
export { stripDirectOverrides } from './stripOverrides'
export { rewriteMargins } from './rewriteMargins'
export { applyStepA } from './applyStepA'
export type { StepAInput, StepAOutput } from './applyStepA'
