export { getGuideline, resolveGuideline, REFERENCES_HEADING_STYLE } from './guidelines'
export type { Guideline, GuidelineSpec } from './guidelines'
export { listGuidelines } from './loadGuideline'
export type { GuidelineMeta } from './loadGuideline'
export { formatReferences, locateReferences, pageForBlock } from './references'
export type { ReferencePagesInput, ReferenceRegion } from './references'
export { getBlocks, blockText } from './blocks'
export { stepD, chunkHeadings, applyHeadingDecisions } from './stepD'
export type { HeadingChunk, HeadingDecision, HeadingDecider, HeadingRole, StepDResult } from './stepD'
export { loadAiConfig } from './ai/config'
export type { AiConfig } from './ai/config'
export { createHeadingDecider } from './ai/headingDecider'
export { unzipDocx, zipDocx } from './docxZip'
export type { UnzippedDocx } from './docxZip'
export { rewriteStyles } from './rewriteStyles'
export { stripDirectOverrides } from './stripOverrides'
export { rewriteMargins } from './rewriteMargins'
export { applyStepA } from './applyStepA'
export type { StepAInput, StepAOutput } from './applyStepA'
